version: '3.8'

services:
  # LibreChat Admin Portal
  admin-portal:
    build:
      context: ./admin-portal
      dockerfile: Dockerfile
    container_name: LibreChat-AdminPortal
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - ADMIN_PORT=4000
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - chat-mongodb
    networks:
      - librechat-network
    restart: unless-stopped
    volumes:
      - ./admin-portal/logs:/app/logs
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  librechat-network:
    external: true
